version: 0.2
phases:
  pre_build:
    commands:
      - echo Get ecr login credentials...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 460234074473.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo build docker image
      - docker build -t handlemycaseformcontainerisation-formsbackend7411eee4-5wli0avhsclo .
      - docker tag handlemycaseformcontainerisation-formsbackend7411eee4-5wli0avhsclo:latest 460234074473.dkr.ecr.eu-west-1.amazonaws.com/handlemycaseformcontainerisation-formsbackend7411eee4-5wli0avhsclo:latest
  post_build:
    commands:
      - Push docker to ecr registry
      - docker push 460234074473.dkr.ecr.eu-west-1.amazonaws.com/handlemycaseformcontainerisation-formsbackend7411eee4-5wli0avhsclo:latest